### ISSUE TITLE
Internet not working on release 0.1

### ISSUE THREAD

**Issue by nitumario** [maksimKorzh/msmd-linux#2]
network.sh is not running because the init file is missing

`
for NETDEV in /sys/class/net/* ; do
  echo "Found network device ${NETDEV##*/}"
  ip link set ${NETDEV##*/} up
  [ ${NETDEV##*/} != lo ] && udhcpc -b -i ${NETDEV##*/} -s /etc/network.sh
done
`

**Comment by maksimKorzh** [comment]
must be a problem with your kernel network driver, try asking chatgpt, it's usually very helpful

**Comment by nitumario** [comment]
Hi! Sorry for late response. The problem is that in the zipped root,  the init file is missing this sequence:
`for NETDEV in /sys/class/net/* ; do echo "Found network device ${NETDEV##*/}" ip link set ${NETDEV##*/} up [ ${NETDEV##*/} != lo ] && udhcpc -b -i ${NETDEV##*/} -s /etc/network.sh done`
After manually adding that the network works like a charm. Cool project btw!

**Comment by maksimKorzh** [comment]
I'm happy you got clear with it, I have an entire series on how to build a custom linux distro from scratch:
https://www.youtube.com/watch?v=EVTw4YqPdKA&list=PLLfIBXQeu3aZuc_0xTE2dY3juntHF5xJY
